dataset: 'fashionmnist'
data_dir: '.'
val_ratio: 0.05
e_class: 'nac' # Using negative autocorrelation evaluator

gpu: '0,1'
n_workers: 8
benchmark: True

n_channels: 1 # number of channels of input images

g_loss_type: 'direct'
weight_norm: 'in'
residual: False

lr_e: !!float 1e-3
lr_g: !!float 2e-4


max_grad_norm_e: 10000.0
max_grad_norm_g: 10000.0
ac_offset: 6

batch_size: 128 # total: 782*64
val_batch_size: 128

output_folder: 'autocorrelation'
